
name: Dev Branch Pipeline
on:
  # Triggers the workflow on push request events but for all the branches except the "main" branch
  push:
    branches:
      - '*'
      - '!main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
# github.sha is commit id that triggered the workflow
# head_commit.message - is the commit message
jobs:
  call-workflow:
    #You call a reusable workflow by using the 'uses' keyword
    uses: hpatel3747/reusable-workflows/.github/workflows/ci-dev-branch.yaml@main


#when calling a workflow 'with:' provides map of inputs that are passed to the called workflow
#to test dev branch, first checkout this file in new branch "main-fe", make changes, and push - which should trigger the workflow
# then merge the main-fe changes in the main branch, to do so checkout to main branch and do "git merge main-fe", then you need to push the
# changes in main branch to github by "git push origin main"
# Following are the steps:
# git checkout main-fe
# make changes in ci-dev-branch.yaml
# commit and push
# test workflow
# git checkout main
# git merge main-fe
# git push origin main